;; This logfile was generated automatically by `xindy'
;; at 02.06.2021  23:48:58
;; Indexstyle: "/tmp/zRPItv3wSO", Rawindex: "/tmp/pCES79bNXZ", Output: "Ch1-Intro.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "€—Ð" -> "A"
Letter-group: "—Ð" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€—Ð" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "—Ð" -> "D"