;; This logfile was generated automatically by `xindy'
;; at 25.07.2019  18:19:14
;; Indexstyle: "/tmp/tojPQjNrMX", Rawindex: "/tmp/lHqnDnD6s0", Output: "mainRep.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "€†¨Ë" -> "A"
Letter-group: "€†´†" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€†¨Ë" -> "A"