;; This logfile was generated automatically by `xindy'
;; at 13.03.2018  08:03:32
;; Indexstyle: "/tmp/Ra82tdkIXE", Rawindex: "/tmp/GxK6RgJjEo", Output: "mainRep.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "€†¨Ë" -> "A"
Letter-group: "€†´†" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€†¨Ë" -> "A"